export const DEFAULT_TIMEOUT_MS = 5000;
export const MS_PER_SECOND = 1000;

export const SESSION_EXPIRES = -1;

export const CHROME_EPOCH_THRESHOLD = 10_000_000_000_000;
export const CHROME_EPOCH_MICROSECONDS = 1_000_000;
export const CHROME_EPOCH_OFFSET_SECONDS = 11_644_473_600;
export const MILLISECOND_THRESHOLD = 10_000_000_000;
export const MAX_UNIX_EPOCH_SECONDS = 253_402_300_799;

export const MAC_EPOCH_DELTA_SECONDS = 978_307_200;
export const BINARY_COOKIE_PAGE_HEADER = 0x00000100;

export const PBKDF2_SALT = "saltysalt";
export const PBKDF2_KEY_LENGTH_BYTES = 16;
export const PBKDF2_IV_FILL = 0x20;
export const PBKDF2_ITERATIONS_DARWIN = 1003;
export const PBKDF2_ITERATIONS_LINUX = 1;

export const SAME_SITE_NONE = 0;
export const SAME_SITE_LAX = 1;
export const SAME_SITE_STRICT = 2;

export const CHROMIUM_META_VERSION_HASH_PREFIX = 24;

export const BINARY_COOKIE_MIN_HEADER_BYTES = 8;
export const BINARY_COOKIE_MIN_PAGE_BYTES = 16;
export const BINARY_COOKIE_MIN_RECORD_BYTES = 48;
export const BINARY_COOKIE_SECURE_FLAG = 0x1;
export const BINARY_COOKIE_HTTP_ONLY_FLAG = 0x4;
export const BINARY_COOKIE_FLAGS_OFFSET = 8;
export const BINARY_COOKIE_URL_OFFSET = 16;
export const BINARY_COOKIE_NAME_OFFSET = 20;
export const BINARY_COOKIE_PATH_OFFSET = 24;
export const BINARY_COOKIE_VALUE_OFFSET = 28;
export const BINARY_COOKIE_EXPIRATION_OFFSET = 40;

export const CHROMIUM_COOKIE_PREFIX_LENGTH_BYTES = 3;
export const AES_HASH_PREFIX_LENGTH_BYTES = 32;
export const GCM_NONCE_LENGTH_BYTES = 12;
export const GCM_TAG_LENGTH_BYTES = 16;
export const GCM_MIN_PAYLOAD_BYTES = 28;
